using UnityEngine;
using System.Collections.Generic;
using TMPro;
using UnityEngine.SceneManagement;

public class Level2_Manager : MonoBehaviour
{

    [Header("Debugging")]
    [SerializeField] private bool showDebugLogs = true;
    [Header("Settings")]
    [SerializeField] private List<Constellation_Data> constellation_data_list;
    [SerializeField] private GameObject star_prefab;
    [SerializeField] private GameObject line_prefab;
    [SerializeField] private LineRenderer drag_line;    // the line the player will be creating when draggin
    [SerializeField] private LineRenderer hint_line;    // the line that will be created for the hints
    [Header("UI")]
    [SerializeField] private TextMeshProUGUI title_text;
    [SerializeField] private GameObject win_panel;
    [SerializeField] private TextMeshProUGUI description;
    [SerializeField] private TextMeshProUGUI myth;
    [SerializeField] private GameObject next_level_button;
    [SerializeField] private GameObject main_menu_button;
    [SerializeField] private GameObject hint_button;
    [SerializeField] private TextMeshProUGUI level_text;
    
    private List<Star_point> spawned_stars = new List<Star_point>();    // list with all the current spawned stars
    private HashSet<string> completed_connections = new HashSet<string>();  // stores all the completed lines/ star connections
    private Star_point starting_star;   // from which star the player started drawing
    private Camera mainCam;
    private Constellation_Data current_level_data;  // ta data tou torinou asterismou
    private int current_level_index; // se pio shmeio ths listas eimaste
    private bool is_hint_active = false;    // ama yparxei active hint on screen
    private Vector2Int hint_pair;       // the hint star pair

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        mainCam = Camera.main;
        if (drag_line == null) Debug.LogError("drag_line is null!");
        if (hint_line == null) Debug.LogError("hint_line is null!");
        if (constellation_data_list.Count == 0) Debug.LogError("no constellation data found!");
        current_level_index = 0;
    }

    public void Load_next_level()
    {
        if (current_level_index < constellation_data_list.Count)
        {
            current_level_index++;
            Load_Level();
        }
        else    // finshed minigame
        {
            SceneManager.LoadScene("Default Screen");
        }
    }

    // Clear previous Constellation and spawn new stars
    public void Load_Level()
    {
        // load the data
        current_level_data = constellation_data_list[current_level_index];

        // Clear last constellation if it exists
        foreach (Transform child in transform)  // game manager children
        {
            if (child == drag_line.transform || child == hint_line.transform)   // dont destroy the drag/hint line 
                continue;
            Destroy(child.gameObject);
        }
        spawned_stars.Clear();
        completed_connections.Clear();
        win_panel.SetActive(false);
        hint_line.gameObject.SetActive(false);

        if (current_level_data != null)
        {
            level_text.text = current_level_index + 1 + "/" + constellation_data_list.Count;
            title_text.text = current_level_data.name;
            description.text = current_level_data.description;
            if (showDebugLogs) Debug.Log($"Loaded: {current_level_data.name} with {current_level_data.star_positions.Count} stars.");
        }

        // Spawn the stars
        for (int i = 0; i < current_level_data.star_positions.Count; i++)
        {
            Vector2 normalized_pos = current_level_data.star_positions[i];
            Vector3 world_pos = Get_World_Position(normalized_pos);

            // create the new stars from the prefab
            GameObject new_Star = Instantiate(star_prefab, world_pos, Quaternion.identity, transform);
            Star_point star_script = new_Star.GetComponent<Star_point>();
            star_script.id = i;     // assign id to the star
            spawned_stars.Add(star_script);
        }
    }


    // Update is called once per frame
    void Update()
    {
        Handle_Input();

    }
    private void Handle_Input()
    {
        // mouse pos from pixels to world coords
        Vector3 mouse_pos = mainCam.ScreenToWorldPoint(Input.mousePosition);
        mouse_pos.z = 0;

        // First Click - Mouse down - We start drawind the line
        if (Input.GetMouseButtonDown(0))
        {
            // cast ray to see if we hit an object
            RaycastHit2D hit = Physics2D.Raycast(mouse_pos, Vector2.zero);
            // check if the object the ray hit(mouse click) was a star
            if (hit.collider != null && hit.collider.TryGetComponent(out Star_point star))
            {
                if (showDebugLogs) Debug.Log($"Star_ID: {star.id} was clicked");
                starting_star = star;
                drag_line.gameObject.SetActive(true);
                drag_line.SetPosition(0, starting_star.transform.position);
                drag_line.SetPosition(1, mouse_pos);
                starting_star.Set_Highlight(true);
            }
        }

        // Drag - update the line
        if (Input.GetMouseButton(0) && starting_star != null)
        {
            drag_line.SetPosition(1, mouse_pos);
        }

        // Mouse Up - Check if there is a connection
        if (Input.GetMouseButtonUp(0) && starting_star != null)
        {
            RaycastHit2D hit = Physics2D.Raycast(mouse_pos, Vector2.zero);
            // bool connectionMade = false;

            if (hit.collider != null && hit.collider.TryGetComponent(out Star_point end_Star))
            {
                if (showDebugLogs) Debug.Log($"2. You stopped draggin at star_id: {end_Star.id}");
                if (end_Star != starting_star)
                {
                    bool valid = Is_Valid_Connection(starting_star.id, end_Star.id);
                    bool exists = Connection_Exists(starting_star.id, end_Star.id);
                    if (valid == false)
                        Global_Audio_Manager.Instance.Play_Error_SFX();
                        
                    //check if connection is valid
                    if (valid && !exists)
                    {
                        if (showDebugLogs) Debug.Log("Connection Succesful!");
                        Draw_Line(starting_star.transform.position, end_Star.transform.position);
                        Register_Connection(starting_star.id, end_Star.id);
                        Global_Audio_Manager.Instance.Play_SFX_correct();
                        Check_Win_Condition();
                    }
                    else
                    {
                        if (showDebugLogs) Debug.Log($"Conection Failed! : Valid={valid}, Exists={exists}");
                    }
                }
                else
                {
                    if (showDebugLogs) Debug.Log("Conection Failed! You clicked on the same star");
                }
            }
            else
            {
                if (showDebugLogs) Debug.Log("Mouse up on empty space.");
            }

            //reset
            starting_star.Set_Highlight(false);
            starting_star = null;
            drag_line.gameObject.SetActive(false);
        }
    }

    // transforms the star positions (0.2,0.3) to Unity coords 
    // this way it will work on all screens and sizes
    private Vector3 Get_World_Position(Vector2 normalized_pos)
    {
        float height = 2f * mainCam.orthographicSize;
        float width = height * mainCam.aspect;

        // calculate new pos based on the center(0,0)
        float x = (normalized_pos.x - 0.5f) * width;
        float y = (normalized_pos.y - 0.5f) * height;

        return new Vector3(x, y, 0);
    }

    // check if the connection bettween 2 stars is valid
    private bool Is_Valid_Connection(int ida, int idb)
    {
        foreach (var pair in current_level_data.connections_index)
        {
            if ((pair.x == ida && pair.y == idb) || (pair.x == idb && pair.y == ida))
                return true;
        }
        return false;
    }

    // check if connection exists bettween 2 numbers
    private bool Connection_Exists(int ida, int idb)
    {
        string key1 = ida + "-" + idb;
        string key2 = idb + "-" + ida;
        return completed_connections.Contains(key1) || completed_connections.Contains(key2);

    }

    // register new connection
    private void Register_Connection(int ida, int idb)
    {
        completed_connections.Add(ida + "-" + idb);
        if (showDebugLogs) Debug.Log($"Connection Registered {ida}-{ida}. Total: {completed_connections.Count}");
        if (is_hint_active && ((hint_pair.x == ida && hint_pair.y == idb) || (hint_pair.x == idb && hint_pair.y == ida)))
        {
            // molis simplirothike to hint
            hint_line.gameObject.SetActive(false);
            is_hint_active = false;
        }
    }

    // Draw a permanent line bettween 2 start to mark a succesful connection
    // input: star coordinates
    private void Draw_Line(Vector3 start, Vector3 end)
    {
        // create a clone of the line prefab pou exoume eidh kanei sto unity editor
        GameObject lineObj = Instantiate(line_prefab, Vector3.zero, Quaternion.identity, transform);    // balto sto (0,0,0) kai paidi toy GameManager

        LineRenderer line_renderer = lineObj.GetComponent<LineRenderer>();
        line_renderer.SetPosition(0, start);
        line_renderer.SetPosition(1, end);
    }

    // Check if the Win Condition is met
    // Win Condition: current connection >= expected connections for this constellation
    private void Check_Win_Condition()
    {
        if (showDebugLogs) Debug.Log($"Check Win: Completed Connections:{completed_connections.Count} / {current_level_data.connections_index.Count}.");

        if (completed_connections.Count >= current_level_data.connections_index.Count)      // constellation completed
        {
            Debug.Log("Constellation Complete");
            win_panel.SetActive(true);
            myth.text = current_level_data.myth;
            Global_Audio_Manager.Instance.Play_Win_SFX();

            Check_Game_Completed(); 

        }
    }
    
    // Is Game completed?
    private void Check_Game_Completed()
    {
        if (current_level_index >= constellation_data_list.Count - 1)
        {
            if (next_level_button != null)
            {
                next_level_button.SetActive(false);
                main_menu_button.SetActive(true);
            }
        }
        else
        {
            if (next_level_button != null)
            {
                next_level_button.SetActive(true);
            }
    }
    }

    // Shows one missing star pair
    public void Show_Hint()
    {
        // if hint is active dont show another hint
        if (is_hint_active)
            return;
        if (showDebugLogs) Debug.Log("Show_Hint was pressed");

        List<Vector2Int> missing_connections = new List<Vector2Int>();

        foreach (var connection in current_level_data.connections_index)
        {
            // if connection does not exist, store it
            if (!Connection_Exists(connection.x, connection.y))
                missing_connections.Add(connection);

            // choose a random 
            if (missing_connections.Count > 0)
            {
                is_hint_active = true;

                int k = Random.Range(0, missing_connections.Count);
                hint_pair = missing_connections[k];

                // draw the hint line
                hint_line.gameObject.SetActive(true);
                // spawned_stars list is in order so star_id = x will be spawned_stars[x]
                hint_line.SetPosition(0, spawned_stars[hint_pair.x].transform.position);
                hint_line.SetPosition(1, spawned_stars[hint_pair.y].transform.position);
            }
        }
    }

    // Load the main menu screen
    public void GoToMainMenu()
    {
        SceneManager.LoadScene("Default Screen");
    }
#if UNITY_EDITOR
    // ŒëœÖœÑœå œÄœÅŒøœÉŒ∏Œ≠œÑŒµŒπ ŒµœÄŒπŒªŒøŒ≥ŒÆ œÉœÑŒø Œ¥ŒµŒæŒØ Œ∫ŒªŒπŒ∫ œÑŒøœÖ Component
    [ContextMenu("üíæ SAVE Star Positions")]
    public void Save_Current_Positions()
    {
        if (current_level_data == null)
        {
            Debug.LogError("ŒîŒµŒΩ œÖœÄŒ¨œÅœáŒµŒπ Level Data!");
            return;
        }

        float height = 2f * mainCam.orthographicSize;
        float width = height * mainCam.aspect;

        // ŒïŒΩŒ∑ŒºŒ≠œÅœâœÉŒ∑ œÑŒ∑œÇ ŒªŒØœÉœÑŒ±œÇ Œ¥ŒµŒ¥ŒøŒºŒ≠ŒΩœâŒΩ ŒºŒµ œÑŒπœÇ œÑœÅŒ≠œáŒøœÖœÉŒµœÇ Œ∏Œ≠œÉŒµŒπœÇ
        for (int i = 0; i < spawned_stars.Count; i++)
        {
            // Œ†Œ±ŒØœÅŒΩŒøœÖŒºŒµ œÑŒ∑ Œ∏Œ≠œÉŒ∑ œÑŒøœÖ Œ±œÉœÑŒµœÅŒπŒøœç Œ±œÄœå œÑŒøŒΩ Œ∫œåœÉŒºŒø (Scene)
            Vector3 worldPos = spawned_stars[i].transform.position;

            // ŒöŒ¨ŒΩŒøœÖŒºŒµ œÑŒ∑ŒΩ Œ±ŒΩœÑŒØœÉœÑœÅŒøœÜŒ∑ œÄœÅŒ¨ŒæŒ∑ Œ±œÄœå œÑŒø Get_World_Position
            // ŒúŒµœÑŒ±œÑœÅŒ≠œÄŒøœÖŒºŒµ œÑŒø World Position œÄŒØœÉœâ œÉŒµ Normalized (0-1)
            float normX = (worldPos.x / width) + 0.5f;
            float normY = (worldPos.y / height) + 0.5f;

            // ŒëœÄŒøŒ∏ŒÆŒ∫ŒµœÖœÉŒ∑ œÉœÑŒø Œ±œÅœáŒµŒØŒø
            current_level_data.star_positions[i] = new Vector2(normX, normY);
        }

        // ŒïŒΩŒ∑ŒºŒ≠œÅœâœÉŒ∑ œÑŒøœÖ Unity œåœÑŒπ Œ±ŒªŒªŒ¨ŒæŒ±ŒºŒµ œÑŒø Œ±œÅœáŒµŒØŒø (Œ≥ŒπŒ± ŒΩŒ± œÑŒø œÉœéœÉŒµŒπ œÉœÑŒøŒΩ Œ¥ŒØœÉŒ∫Œø)
        UnityEditor.EditorUtility.SetDirty(current_level_data);
    }
#endif
}